# General Jekyll Config
highlighter: true
url: http://phndiaye.github.io
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
permalink: /:title.html

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#34495e'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: phndiaye
    stackoverflow: 1570927
    twitter: phndiaye

  # "Hi, I'm _______"
  name: Philippe Ndiaye
  email: me@iamphinson.com
  tagline: "weak opinions, strongly held"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-39753527-1

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true
